version: '3.8'

services:
  api:
    build:
      context: .
    container_name: express_app
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRES_IN: ${JWT_ACCESS_EXPIRES_IN}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
      RESET_TOKEN_EXPIRES_IN: ${RESET_TOKEN_EXPIRES_IN}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      PLATFORM_COMMISSION_RATE: ${PLATFORM_COMMISSION_RATE}
      DISPUTE_PENALTY_RATE: ${DISPUTE_PENALTY_RATE}
    command: npm run dev

